In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm
import numpy as np
from statsmodels.sandbox.regression.predstd import wls_prediction_std

In [2]:
df = pd.read_csv("ACS_16_5YR_B27001_with_ann.csv",
                usecols = ['GEO.id','GEO.id2','GEO.display-label',
                           'HD01_VD11','HD01_VD14','HD01_VD17','HD01_VD20','HD01_VD23',
                            'HD01_VD26','HD01_VD29','HD01_VD39','HD01_VD42',
                           'HD01_VD45','HD01_VD48','HD01_VD51','HD01_VD54','HD02_VD57'])

In [3]:
df = df[1:]

In [4]:
df[['HD01_VD11','HD01_VD14','HD01_VD17','HD01_VD20','HD01_VD23',
                            'HD01_VD26','HD01_VD29','HD01_VD39','HD01_VD42',
                           'HD01_VD45','HD01_VD48','HD01_VD51','HD01_VD54','HD02_VD57']] = df[['HD01_VD11','HD01_VD14','HD01_VD17','HD01_VD20','HD01_VD23',
                            'HD01_VD26','HD01_VD29','HD01_VD39','HD01_VD42',
                           'HD01_VD45','HD01_VD48','HD01_VD51','HD01_VD54','HD02_VD57']].astype(float)

In [5]:
df.dtypes

GEO.id                object
GEO.id2               object
GEO.display-label     object
HD01_VD11            float64
HD01_VD14            float64
HD01_VD17            float64
HD01_VD20            float64
HD01_VD23            float64
HD01_VD26            float64
HD01_VD29            float64
HD01_VD39            float64
HD01_VD42            float64
HD01_VD45            float64
HD01_VD48            float64
HD01_VD51            float64
HD01_VD54            float64
HD02_VD57            float64
dtype: object

In [6]:
df['uninsured adult male'] = df[[ 'HD01_VD11','HD01_VD14','HD01_VD17','HD01_VD20','HD01_VD23',
                            'HD01_VD26','HD01_VD29']].sum(axis=1)

In [7]:
df['uninsured adult female'] = df[['HD01_VD39','HD01_VD42',
                           'HD01_VD45','HD01_VD48','HD01_VD51','HD01_VD54','HD02_VD57']].sum(axis=1)

In [8]:
df_uninsured = df[['GEO.id','GEO.id2','GEO.display-label','uninsured adult male','uninsured adult female']]

In [9]:
df_uninsured['uninsured total'] = df_uninsured['uninsured adult male'] + df_uninsured['uninsured adult female']

/Users/leiao/.pyenv/versions/3.7.1/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [10]:
df_uninsured

,GEO.id,GEO.id2,GEO.display-label,uninsured adult male,uninsured adult female,uninsured total
1,0400000US01,01,Alabama,269564.0,243917.0,513481.0
2,0400000US02,02,Alaska,54543.0,44453.0,98996.0
3,0400000US04,04,Arizona,407484.0,331937.0,739421.0
4,0400000US05,05,Arkansas,172318.0,152476.0,324794.0
5,0400000US06,06,California,2379462.0,1920198.0,4299660.0
6,0400000US08,08,Colorado,278783.0,215320.0,494103.0
7,0400000US09,09,Connecticut,128676.0,95806.0,224482.0
8,0400000US10,10,Delaware,33780.0,26548.0,60328.0
9,0400000US11,11,District of Columbia,18913.0,12067.0,30980.0
10,0400000US12,12,Florida,1520037.0,1319802.0,2839839.0
11,0400000US13,13,Georgia,708650.0,662897.0,1371547.0
12,0400000US15,15,Hawaii,35142.0,27245.0,62387.0
13,0400000US16,16,Idaho,97943.0,89118.0,187061.0
14,0400000US17,17,Illinois,642979.0,493010.0,1135989.0
15,0400000US18,18,Indiana,337020.0,295395.0,632415.0
16,0400000US19,19,Iowa,95371.0,74176.0,169547.0
17,0400000US20,20,Kansas,135342.0,122563.0,257905.0
18,0400000US21,21,Kentucky,200231.0,168132.0,368363.0
19,0400000US22,22,Louisiana,305860.0,281763.0,587623.0
20,0400000US23,23,Maine,62422.0,47687.0,110109.0
21,0400000US24,24,Maryland,239425.0,185304.0,424729.0
22,0400000US25,25,Massachusetts,121660.0,74015.0,195675.0
23,0400000US26,26,Michigan,420543.0,324000.0,744543.0
24,0400000US27,27,Minnesota,160898.0,113509.0,274407.0
25,0400000US28,28,Mississippi,200667.0,185020.0,385687.0
26,0400000US29,29,Missouri,308469.0,277060.0,585529.0
27,0400000US30,30,Montana,63726.0,55432.0,119158.0
28,0400000US31,31,Nebraska,82754.0,71688.0,154442.0
29,0400000US32,32,Nevada,202331.0,175704.0,378035.0
30,0400000US33,33,New Hampshire,55916.0,45727.0,101643.0
31,0400000US34,34,New Jersey,467778.0,378197.0,845975.0
32,0400000US35,35,New Mexico,140451.0,119159.0,259610.0
33,0400000US36,36,New York,886074.0,642426.0,1528500.0
34,0400000US37,37,North Carolina,618826.0,544104.0,1162930.0
35,0400000US38,38,North Dakota,27780.0,21568.0,49348.0
36,0400000US39,39,Ohio,477170.0,369804.0,846974.0
37,0400000US40,40,Oklahoma,267387.0,244927.0,512314.0
38,0400000US41,41,Oregon,205056.0,165177.0,370233.0
39,0400000US42,42,Pennsylvania,489128.0,379445.0,868573.0
40,0400000US44,44,Rhode Island,44371.0,31173.0,75544.0
41,0400000US45,45,South Carolina,300413.0,265706.0,566119.0
42,0400000US46,46,South Dakota,40588.0,33381.0,73969.0
43,0400000US47,47,Tennessee,379131.0,304982.0,684113.0
44,0400000US48,48,Texas,2225730.0,2100240.0,4325970.0
45,0400000US49,49,Utah,144902.0,128195.0,273097.0
46,0400000US50,50,Vermont,18593.0,11543.0,30136.0
47,0400000US51,51,Virginia,405878.0,358045.0,763923.0
48,0400000US53,53,Washington,345296.0,270487.0,615783.0
49,0400000US54,54,West Virginia,88082.0,74028.0,162110.0
50,0400000US55,55,Wisconsin,205593.0,148906.0,354499.0
51,0400000US56,56,Wyoming,33716.0,29496.0,63212.0
52,0400000US72,72,Puerto Rico,122104.0,73447.0,195551.0

In [11]:
df_pop = pd.read_csv("TEST-census-data-for-edit-test.csv")

In [12]:
df_pop.head()

,GEO.id,GEO.id2,GEO.display-label,HC01_VC03,HC02_VC03,HC03_VC03,HC01_VC04,HC02_VC04,HC03_VC04,HC01_VC05,...,HC03_VC104,HC01_VC108,HC02_VC108,HC03_VC108,HC01_VC109,HC02_VC109,HC03_VC109,HC01_VC110,HC02_VC110,HC03_VC110
0,Id,Id2,Geography,2012-2016 Estimates; SEX AND AGE - Total popul...,2007-2011 Estimates; SEX AND AGE - Total popul...,Statistical Significance; SEX AND AGE - Total ...,2012-2016 Estimates; SEX AND AGE - Total popul...,2007-2011 Estimates; SEX AND AGE - Total popul...,Statistical Significance; SEX AND AGE - Total ...,2012-2016 Estimates; SEX AND AGE - Total popul...,...,Statistical Significance; HISPANIC OR LATINO A...,"2012-2016 Estimates; CITIZEN, VOTING AGE POPUL...","2007-2011 Estimates; CITIZEN, VOTING AGE POPUL...","Statistical Significance; CITIZEN, VOTING AGE ...","2012-2016 Estimates; CITIZEN, VOTING AGE POPUL...","2007-2011 Estimates; CITIZEN, VOTING AGE POPUL...","Statistical Significance; CITIZEN, VOTING AGE ...","2012-2016 Estimates; CITIZEN, VOTING AGE POPUL...","2007-2011 Estimates; CITIZEN, VOTING AGE POPUL...","Statistical Significance; CITIZEN, VOTING AGE ..."
1,0400000US01,1,Alabama,4841164,4747424,c,48.5,48.5,*,51.5,...,*,3639493,3514599,*,47.6,47.4,*,52.4,52.6,*
2,0400000US02,2,Alaska,736855,700703,c,52.3,51.9,*,47.7,...,*,527811,493714,*,52.8,52,*,47.2,48,*
3,0400000US04,4,Arizona,6728577,6337373,c,49.7,49.7,*,50.3,...,*,4613575,4197367,*,49.2,49,*,50.8,51,*
4,0400000US05,5,Arkansas,2968472,2895928,c,49.1,49.1,NaN,50.9,...,*,2175338,2108932,*,48.3,48.1,*,51.7,51.9,*

In [13]:
df_pop = df_pop[['GEO.id','GEO.id2','GEO.display-label','HC01_VC03','HC01_VC33','HC01_VC34']]

In [14]:
df_pop = df_pop[1:]

In [15]:
df_pop[['HC01_VC03','HC01_VC33','HC01_VC34']] = df_pop[['HC01_VC03','HC01_VC33','HC01_VC34']].astype(float)

In [16]:
df_pop

,GEO.id,GEO.id2,GEO.display-label,HC01_VC03,HC01_VC33,HC01_VC34
1,0400000US01,1,Alabama,4841164.0,47.7,52.3
2,0400000US02,2,Alaska,736855.0,52.6,47.4
3,0400000US04,4,Arizona,6728577.0,49.3,50.7
4,0400000US05,5,Arkansas,2968472.0,48.4,51.6
5,0400000US06,6,California,38654206.0,49.2,50.8
6,0400000US08,8,Colorado,5359295.0,49.9,50.1
7,0400000US09,9,Connecticut,3588570.0,48.1,51.9
8,0400000US10,10,Delaware,934695.0,47.7,52.3
9,0400000US11,11,District of Columbia,659009.0,46.8,53.2
10,0400000US12,12,Florida,19934451.0,48.3,51.7
11,0400000US13,13,Georgia,10099320.0,48.0,52.0
12,0400000US15,15,Hawaii,1413673.0,49.9,50.1
13,0400000US16,16,Idaho,1635483.0,49.7,50.3
14,0400000US17,17,Illinois,12851684.0,48.5,51.5
15,0400000US18,18,Indiana,6589578.0,48.7,51.3
16,0400000US19,19,Iowa,3106589.0,49.2,50.8
17,0400000US20,20,Kansas,2898292.0,49.3,50.7
18,0400000US21,21,Kentucky,4411989.0,48.6,51.4
19,0400000US22,22,Louisiana,4645670.0,48.2,51.8
20,0400000US23,23,Maine,1329923.0,48.4,51.6
21,0400000US24,24,Maryland,5959902.0,47.7,52.3
22,0400000US25,25,Massachusetts,6742143.0,47.8,52.2
23,0400000US26,26,Michigan,9909600.0,48.6,51.4
24,0400000US27,27,Minnesota,5450868.0,49.3,50.7
25,0400000US28,28,Mississippi,2989192.0,47.8,52.2
26,0400000US29,29,Missouri,6059651.0,48.4,51.6
27,0400000US30,30,Montana,1023391.0,49.9,50.1
28,0400000US31,31,Nebraska,1881259.0,49.2,50.8
29,0400000US32,32,Nevada,2839172.0,50.0,50.0
30,0400000US33,33,New Hampshire,1327503.0,49.1,50.9
31,0400000US34,34,New Jersey,8915456.0,48.1,51.9
32,0400000US35,35,New Mexico,2082669.0,49.0,51.0
33,0400000US36,36,New York,19697457.0,47.8,52.2
34,0400000US37,37,North Carolina,9940828.0,47.9,52.1
35,0400000US38,38,North Dakota,736162.0,51.2,48.8
36,0400000US39,39,Ohio,11586941.0,48.3,51.7
37,0400000US40,40,Oklahoma,3875589.0,49.0,51.0
38,0400000US41,41,Oregon,3982267.0,49.0,51.0
39,0400000US42,42,Pennsylvania,12783977.0,48.3,51.7
40,0400000US44,44,Rhode Island,1054491.0,47.8,52.2
41,0400000US45,45,South Carolina,4834605.0,47.9,52.1
42,0400000US46,46,South Dakota,851058.0,50.0,50.0
43,0400000US47,47,Tennessee,6548009.0,48.1,51.9
44,0400000US48,48,Texas,26956435.0,49.1,50.9
45,0400000US49,49,Utah,2948427.0,49.8,50.2
46,0400000US50,50,Vermont,626249.0,48.8,51.2
47,0400000US51,51,Virginia,8310301.0,48.6,51.4
48,0400000US53,53,Washington,7073146.0,49.5,50.5
49,0400000US54,54,West Virginia,1846092.0,49.0,51.0
50,0400000US55,55,Wisconsin,5754798.0,49.3,50.7
51,0400000US56,56,Wyoming,583029.0,50.8,49.2
52,0400000US72,72,Puerto Rico,3529385.0,46.8,53.2

In [17]:
df_pop['adult male'] = round(df_pop['HC01_VC03'] * df_pop['HC01_VC33'] / 100)

In [18]:
df_pop['adult female'] = round(df_pop['HC01_VC03'] * df_pop['HC01_VC34'] / 100)

In [19]:
df_pop['total'] = df_pop['adult male'] + df_pop['adult female']

In [20]:
df_merge = pd.merge(df_uninsured,df_pop, on='GEO.id')

In [21]:
df_merge = df_merge.drop(['HC01_VC03','HC01_VC33','HC01_VC34'], axis=1)

In [22]:
df_merge['uninsured rate'] = round(df_merge['uninsured total'] / df_merge['total'] * 100)

In [23]:
df_merge['male uninsured rate'] = round(df_merge['uninsured adult male'] / df_merge['adult male'] * 100)

In [24]:
df_merge['female uninsured rate'] = round(df_merge['uninsured adult female'] / df_merge['adult female'] * 100)

In [25]:
df_merge['gender gap'] = df_merge['male uninsured rate'] - df_merge['female uninsured rate']

In [26]:
df_merge = df_merge.sort_values(by='uninsured rate',ascending=False)

In [27]:
df_merge.to_csv("uninsured adults.csv", index=False)

In [28]:
df_merge

,GEO.id,GEO.id2_x,GEO.display-label_x,uninsured adult male,uninsured adult female,uninsured total,GEO.id2_y,GEO.display-label_y,adult male,adult female,total,uninsured rate,male uninsured rate,female uninsured rate,gender gap
43,0400000US48,48,Texas,2225730.0,2100240.0,4325970.0,48,Texas,13235610.0,13720825.0,26956435.0,16.0,17.0,15.0,2.0
9,0400000US12,12,Florida,1520037.0,1319802.0,2839839.0,12,Florida,9628340.0,10306111.0,19934451.0,14.0,16.0,13.0,3.0
10,0400000US13,13,Georgia,708650.0,662897.0,1371547.0,13,Georgia,4847674.0,5251646.0,10099320.0,14.0,15.0,13.0,2.0
18,0400000US22,22,Louisiana,305860.0,281763.0,587623.0,22,Louisiana,2239213.0,2406457.0,4645670.0,13.0,14.0,12.0,2.0
36,0400000US40,40,Oklahoma,267387.0,244927.0,512314.0,40,Oklahoma,1899039.0,1976550.0,3875589.0,13.0,14.0,12.0,2.0
28,0400000US32,32,Nevada,202331.0,175704.0,378035.0,32,Nevada,1419586.0,1419586.0,2839172.0,13.0,14.0,12.0,2.0
1,0400000US02,02,Alaska,54543.0,44453.0,98996.0,2,Alaska,387586.0,349269.0,736855.0,13.0,14.0,13.0,1.0
24,0400000US28,28,Mississippi,200667.0,185020.0,385687.0,28,Mississippi,1428834.0,1560358.0,2989192.0,13.0,14.0,12.0,2.0
26,0400000US30,30,Montana,63726.0,55432.0,119158.0,30,Montana,510672.0,512719.0,1023391.0,12.0,12.0,11.0,1.0
40,0400000US45,45,South Carolina,300413.0,265706.0,566119.0,45,South Carolina,2315776.0,2518829.0,4834605.0,12.0,13.0,11.0,2.0
33,0400000US37,37,North Carolina,618826.0,544104.0,1162930.0,37,North Carolina,4761657.0,5179171.0,9940828.0,12.0,13.0,11.0,2.0
31,0400000US35,35,New Mexico,140451.0,119159.0,259610.0,35,New Mexico,1020508.0,1062161.0,2082669.0,12.0,14.0,11.0,3.0
50,0400000US56,56,Wyoming,33716.0,29496.0,63212.0,56,Wyoming,296179.0,286850.0,583029.0,11.0,11.0,10.0,1.0
0,0400000US01,01,Alabama,269564.0,243917.0,513481.0,1,Alabama,2309235.0,2531929.0,4841164.0,11.0,12.0,10.0,2.0
2,0400000US04,04,Arizona,407484.0,331937.0,739421.0,4,Arizona,3317188.0,3411389.0,6728577.0,11.0,12.0,10.0,2.0
4,0400000US06,06,California,2379462.0,1920198.0,4299660.0,6,California,19017869.0,19636337.0,38654206.0,11.0,13.0,10.0,3.0
3,0400000US05,05,Arkansas,172318.0,152476.0,324794.0,5,Arkansas,1436740.0,1531732.0,2968472.0,11.0,12.0,10.0,2.0
12,0400000US16,16,Idaho,97943.0,89118.0,187061.0,16,Idaho,812835.0,822648.0,1635483.0,11.0,12.0,11.0,1.0
14,0400000US18,18,Indiana,337020.0,295395.0,632415.0,18,Indiana,3209124.0,3380454.0,6589578.0,10.0,11.0,9.0,2.0
25,0400000US29,29,Missouri,308469.0,277060.0,585529.0,29,Missouri,2932871.0,3126780.0,6059651.0,10.0,11.0,9.0,2.0
42,0400000US47,47,Tennessee,379131.0,304982.0,684113.0,47,Tennessee,3149592.0,3398417.0,6548009.0,10.0,12.0,9.0,3.0
47,0400000US53,53,Washington,345296.0,270487.0,615783.0,53,Washington,3501207.0,3571939.0,7073146.0,9.0,10.0,8.0,2.0
41,0400000US46,46,South Dakota,40588.0,33381.0,73969.0,46,South Dakota,425529.0,425529.0,851058.0,9.0,10.0,8.0,2.0
16,0400000US20,20,Kansas,135342.0,122563.0,257905.0,20,Kansas,1428858.0,1469434.0,2898292.0,9.0,9.0,8.0,1.0
13,0400000US17,17,Illinois,642979.0,493010.0,1135989.0,17,Illinois,6233067.0,6618617.0,12851684.0,9.0,10.0,7.0,3.0
48,0400000US54,54,West Virginia,88082.0,74028.0,162110.0,54,West Virginia,904585.0,941507.0,1846092.0,9.0,10.0,8.0,2.0
37,0400000US41,41,Oregon,205056.0,165177.0,370233.0,41,Oregon,1951311.0,2030956.0,3982267.0,9.0,11.0,8.0,3.0
5,0400000US08,08,Colorado,278783.0,215320.0,494103.0,8,Colorado,2674288.0,2685007.0,5359295.0,9.0,10.0,8.0,2.0
44,0400000US49,49,Utah,144902.0,128195.0,273097.0,49,Utah,1468317.0,1480110.0,2948427.0,9.0,10.0,9.0,1.0
30,0400000US34,34,New Jersey,467778.0,378197.0,845975.0,34,New Jersey,4288334.0,4627122.0,8915456.0,9.0,11.0,8.0,3.0
46,0400000US51,51,Virginia,405878.0,358045.0,763923.0,51,Virginia,4038806.0,4271495.0,8310301.0,9.0,10.0,8.0,2.0
22,0400000US26,26,Michigan,420543.0,324000.0,744543.0,26,Michigan,4816066.0,5093534.0,9909600.0,8.0,9.0,6.0,3.0
32,0400000US36,36,New York,886074.0,642426.0,1528500.0,36,New York,9415384.0,10282073.0,19697457.0,8.0,9.0,6.0,3.0
29,0400000US33,33,New Hampshire,55916.0,45727.0,101643.0,33,New Hampshire,651804.0,675699.0,1327503.0,8.0,9.0,7.0,2.0
17,0400000US21,21,Kentucky,200231.0,168132.0,368363.0,21,Kentucky,2144227.0,2267762.0,4411989.0,8.0,9.0,7.0,2.0
27,0400000US31,31,Nebraska,82754.0,71688.0,154442.0,31,Nebraska,925579.0,955680.0,1881259.0,8.0,9.0,8.0,1.0
19,0400000US23,23,Maine,62422.0,47687.0,110109.0,23,Maine,643683.0,686240.0,1329923.0,8.0,10.0,7.0,3.0
34,0400000US38,38,North Dakota,27780.0,21568.0,49348.0,38,North Dakota,376915.0,359247.0,736162.0,7.0,7.0,6.0,1.0
35,0400000US39,39,Ohio,477170.0,369804.0,846974.0,39,Ohio,5596493.0,5990448.0,11586941.0,7.0,9.0,6.0,3.0
38,0400000US42,42,Pennsylvania,489128.0,379445.0,868573.0,42,Pennsylvania,6174661.0,6609316.0,12783977.0,7.0,8.0,6.0,2.0
39,0400000US44,44,Rhode Island,44371.0,31173.0,75544.0,44,Rhode Island,504047.0,550444.0,1054491.0,7.0,9.0,6.0,3.0
20,0400000US24,24,Maryland,239425.0,185304.0,424729.0,24,Maryland,2842873.0,3117029.0,5959902.0,7.0,8.0,6.0,2.0
49,0400000US55,55,Wisconsin,205593.0,148906.0,354499.0,55,Wisconsin,2837115.0,2917683.0,5754798.0,6.0,7.0,5.0,2.0
6,0400000US09,09,Connecticut,128676.0,95806.0,224482.0,9,Connecticut,1726102.0,1862468.0,3588570.0,6.0,7.0,5.0,2.0
7,0400000US10,10,Delaware,33780.0,26548.0,60328.0,10,Delaware,445850.0,488845.0,934695.0,6.0,8.0,5.0,3.0
51,0400000US72,72,Puerto Rico,122104.0,73447.0,195551.0,72,Puerto Rico,1651752.0,1877633.0,3529385.0,6.0,7.0,4.0,3.0
15,0400000US19,19,Iowa,95371.0,74176.0,169547.0,19,Iowa,1528442.0,1578147.0,3106589.0,5.0,6.0,5.0,1.0
45,0400000US50,50,Vermont,18593.0,11543.0,30136.0,50,Vermont,305610.0,320639.0,626249.0,5.0,6.0,4.0,2.0
8,0400000US11,11,District of Columbia,18913.0,12067.0,30980.0,11,District of Columbia,308416.0,350593.0,659009.0,5.0,6.0,3.0,3.0
23,0400000US27,27,Minnesota,160898.0,113509.0,274407.0,27,Minnesota,2687278.0,2763590.0,5450868.0,5.0,6.0,4.0,2.0
11,0400000US15,15,Hawaii,35142.0,27245.0,62387.0,15,Hawaii,705423.0,708250.0,1413673.0,4.0,5.0,4.0,1.0
21,0400000US25,25,Massachusetts,121660.0,74015.0,195675.0,25,Massachusetts,3222744.0,3519399.0,6742143.0,3.0,4.0,2.0,2.0